Feat jaco2 robot (#2)
* Added option to set default settings or not in constructor vpRobotBebop2 class.
Added options to set tag size and tag distance in servoBebop2.cpp.
Added some more support for 720p (still bugged).

* Fixed 720p streaming by adding SPS and PPS parameters management.

* Adding tutorial for Bebop 2 visual servoing (not finished yet).

* Upgrade ios tutorial with the latest OpenCV 4.1.1 ios framework version available

* Modify vpPose lambda value to 0.9 to have at least 2 iterations to converge. With lambda=1, if everything is perfect we should converge in 1 iteration. This change was introduced after a discussion with FC.

* Upgrade windows tutorial with OpenCV 4.1.1

* Fix warning (cast from double to int) occuring on windows

* Add VirtuoseAPI v3_98 auto detection

* Improve franka pbvs example displaying in the image the trajectory of the tag corners and cog

* Introduce franka ibvs example

* Improve franka pbvs tutorial adding images to show the servo behavior

* Introduce new franka ibvs tutorial

* Remove useless header

* Adding 720p options in image grabber. Updated tutorials (image grabber and camera calibration) accordingly.
Updated Bebop 2 servoing tutorial.

* Fix pointcloud computation when align parameter is set with librealsense2.

* Add infrared1 / infrared2 acquisition for all the methods. Do not transform pointcloud if extrinsic is identity.

* displayLine() allows now to display a segment (default) or a line passing through 2 points thanks to an additional parameter

* Introduce new vanishing point features from polar coordinates

* Bebop2 visual servoing example

* Introduce Parrot Bebop2 IBVS tutorial

* Revert "Introduce new vanishing point features from polar coordinates"

This reverts commit 376ff8bc24dee30657d53a1ea5470d47a33378a7.

* Revert "displayLine() allows now to display a segment (default) or a line passing through 2 points thanks to an additional parameter"

This reverts commit ab7d824f5cfdf862e3e86a95f40ea80eb4c0244e.

* Explicit ffmpeg detection and usage to decode bebop2 video stream instead of using opencv that could be build with or without ffmpeg support
- ffmpeg detection is only activated when ARSDK3 is found

* Improve tutorial to explain how to build on OSX

* Fix build when ffmpeg not available

* Add bebop video and image with the frames

* Add IBVS controller description

* Fix doxygen warning

* Improved comments in various files, sorted functions in .h for Doxygen

* Improved documentation and servoBebop2 tutorial

* Improved help message for tutorial-grabber-bebop2.cpp

* Initial commit to introduce the framework to support Kinova Jaco2 robot
- This work relates PR #619 initiated by Zubair Arif research scholar at Harbin institute of technology

* Update with last changes

* Simplify testRealSense2_D435.cpp by splitting it into three files.

* Added option to change IP of the drone to connect to in all concerned programs and updated documentation to explain how to change internal Bebop 2 IP.
Also updated testRobotBebop2.cpp.

* Updating tutorial to explain how to connect to multiple drones with a single computer.

* Fix warning: unused varaible

* Modify tutorial sections

* Fix doxygen 1.8.16 warnings and modify youtube video addresses for those that are no more displayed

* Add Catch2 header-only test framework.

* Quick fix, remove short command line options to avoid potential issue with same command line options in ViSP tests.

* Catch2 for unit tests and micro-benchmarking.

* Use velocity twist term instead of skew

* Introduce vp_get_interface_link_libraries() mainly for ustk to propagate VTK and Qt5 link interfaces.

* Remove explicit setting -std=c++11 compiler option with librealsense since this option is propagated by ViSP

* Make a ref to visp_ros corresponding tutorial

* Fix doxygen issue

* Update vpRobotTemplate

* Modify FlyCapture SDK detection removing default path to be able to handle x64 or Win32 libraries under windows. Without NO_DEFAULT_PATH win32 library is always detected under Windows even if msvc 64 bit is used leading to link issues

* Use cache friendly matrix transpose algorithm. Convert some old performance test code to use Catch2 framework.

* Fix warp homography to ensure that denominator is never equal to zero

* Optimize MI Inverse Compositional to end optimization loop when residual doesn't evolve any more

*  Optimize MI Forward Additionnal to end optimization loop when residual doesn't evolve anymore

* Fix potential build issue

* Optimize computeDenom() and add sanity check on warpXInv()

* Introduce license and readme files

* Introduce an empty line at the end of the file

* Match declatation and definition

* Remove ctest -c (click) -d (display) default options to perf test that are using Catch2 in order to be able to consider Catch2 short options -c and -d without interfering with ctest

* Add comparison operator for vpArray2D.

* Rollback to simple matrix transpose.

* Use Catch2 to test Eigen conversion.

* Code refactoring
- delete useless deletePosEvalRMS() function
- migrate computeEvalRMS() and initPosEvalRMS() functions in mother class vpTemplateTracker to avoid code recopy
- introduce setThresholdResidualDifference() that allows to modify the default residual difference that allows to end optimiization loop
- make setThresholdRMS() deprecated
- remove useless code that was commented

* Remove useless code that was commented

* Speed up optimization loop
- introduce threshold to check if residual difference between 2 successive iterations is lower than a threshold to end optimization
- remove useless commented code

* Introduce new options for tracking introspection
-r to be able to remove tracking reset at iteration 10
-L to save the number of iterations needed by optimization loop
-s <threshold> to be able to tune the threshold used to end optimization loop when residual difference between 2 iterations is lower than this value

* Fix typo

* Introduce residual thresholding to end optimization loop

* Fix MI ESM tracker introducing vpTemplateTrackerMIBSpline::computeProbabilities()

* Remove useless multiplication

* Remove old style cast

* Remove test with ESM and non compatible warp function

* Avoid filtering twice the same image

* Update with last changes

* Fix build on platform that has only cxx98 standard

* Update with instructions to build ViSP for Android on Windows
- update tutorials
- modify gradle.properties to use -Xmx1024m heap size to avoid an issue on
  windows: "Could not reserve enough space for 1572864KB object heap".

* Introduce images of potential pcl issues

* Update inspired from OpenCV equivalent file

* Update to use last gradle release

* Fix doxygen warning

* updated correct code for findJaco2.cmake file to find the jaco2 SDK library files during cmake configure process.

* Fix compat with python 3

* Introduce config file for NDK 20.0

* Update Java and Android tutorial mainly for Windows

* Updates for Ubuntu

* Start introducing Kinova interface

* Introduce cartesian position and velocity control

* Various fixes for Ubuntu

* Fix warning with clang 11.0.0 on macos catalina

* Remove commented line

* Explicit use of std::placeholders

* Matrix operation optimization
- initialize matrices to zero only when needed
- optimize scalar multiplication and division by 1
- optimize HLM (effective for big matrices)

* Optimize template tracker
- fuse for loops
- introduce internal vars to avoid computing multiple times the same operation
- use std::vector to avoid memory allocation with new/delete
- remove useless code that induced al lot of useless computations (ie. computeDenom() for example)
- remove commented code

* Fix changes introduced in PR #635 to be able to build with g++ 4.6.3 (Ubuntu 12.04)

* Fix build with PCL 1.7.1 that comes with Ubuntu 12.04

* Disable c++11 which implementation is too much experimental with g++ 4.6

* Fix error: using declaration xxx conflicts with a previous using declaration that occurs with g++ 4.6.3 on Ubuntu 12.04

* Turn warning multi-line comment off due to pcl-1.8

* Matrix transpose using block tiling and AVX instructions if available for large matrix.

* Fix Eigen warnings. Do not run performance with ctest (too long computation time for cdash).

* Avoid having duplicate entries for BLAS variable when configuring cmake multiple times.

* Zero the upper 128 bits of all YMM registers to avoid potential issue with AVX-SSE transition penalties.

* Replace pseudorandom number generator to remove global state and with better performance. Add coresponding tests. Update vpPoseRansac to use vpUniRand to fix potential issue with thread safety and sporadic segfault on ARM CI.

* Fix floating-point comparisons in vpMatrix.

* Remove unused class member var

* Degeneracy in vpLinProg::rowReduction + faster QP by picking QR over SVD when possible

* replace NULL by nullptr

* Turn warnings off due to PCL and Ogre 3td parties on Ubuntu 18.04

* Remove unused private field

* When g++ 4.6 is detected we disable c++11

* Fix cxx11 detection

* Remove changing last frame index when an empty frame is reached. Allows to pass over empty frames.

* Upgrade to apriltag 3.1.1

* Fix doc and introduce OpenCV 4.1.2 usage

* Introduce a flag to detect if last frame is unknown
- if unknown, we set the last frame to the first empty frame that is encountered
- else, we skip empty frames

* Fix video name in helper message

* Refactoring
- use std::string instead of char *
- prefix class member vars with m_ to match ViSP coding style

* Introduce possible click to stop video display

* Fix build with msvc16

* Turn warnings off with msvc16

* Remove printings

* Fix build with big family tags

* Fix build error on windows due to arround winsock2.h include file usage
- error C2011: 'sockaddr' : redefinition of type 'struct'

* Fix warning C6308 detected with msvc16

* Introduce FLIR PTU-SDK detection and vpRobotFlirPtu class to control FLIR pan-tilt unit

* Add cerial.h include location detection

* Introduce joint control

* Improve cxx11 detection
- add cxx_override feature detection to enable cxx
- without this feature vpException doesn't build when cxx11 is enabled

* Fix undefined reference to UINT32_MAX with g++ 4.6.3

* Fix doxygen doc

* Add performance test for Apriltag detection.

* Fix cxx standard detection for compat with cmake version < 3.8.0
- with cmake version >= 3.8.0, CMAKE_CXX<standard>_COMPILE_FEATURES includes `cxx_std_<standard>` string with standard in [98,11,14,17]
- this is not the case with older cmake versions
- This commit removes finding `cxx_std_<standard>` in CMAKE_CXX<standard>_COMPILE_FEATURES

* Fix warning detected on Ubuntu 12.04

* Introduce vectors as internal vars

* Introduce joint velocity control

* Introduce options and velocity control example

* Fix build with msvc

* Fix exception error message

* Fix build issue with Biclops 3rd party support

* Avoid using -std=gnu++11

* Fix build for UWP with msvc15

* Fix build for UWP with msvc15

* Fix warnings for UWP with msvc15

* Fix build issue C1128 when building perf*.cpp with msvc15 in Debug configuration

* Turn LNK4099 warning off that occurs with msvc15 in Debug configuration when VTK is used as 3rd party

* Fix warning: missing initializer for member ‘pt::slope

* Remove useless files from build

* Various improvements:
- Introduce network info getters
- Get/Set pan/tilt position limits

* Improve example

* Get FLIR PTU SDK version

* Catch CTRL-C signal to stop PTU motion when velocity control

* fix vpVideoReader to enable MTS Format reading

* Update with last changes

* Migrate to new CDash 2.6.0 server

* Remove no optimizattion attribute in source code
- it's already done in the CMakeLists.txt file
- it produces a warning on osx ci.inria.fr: unknown attribute 'optnone' ignored [-Wattributes]

* Turn off warnings due to librealsense2 3rd party when building servoFrankaIBVS.cpp

* Fix warning private field 'm_lastframe_unknown' is not used when build without OpenCV 3rd party

* Fix apriltag memory leak detected with valgrind running testAprilTag.cpp

* Fix warning detected on Debian sid
- tested with g++ (Debian 9.2.1-19) 9.2.1 20191109
- warnings were due to Ogre3D and Eigen3 3rd party

Signed-off-by: Fabien Spindler <Fabien.Spindler@inria.fr>

* Minor improvements in image moments

* Small fix in vpFeatureMomentAlpha

* Add warpImage() function for affine and perspective image transformations.

* introduced mixt_frame and camera frame support

* Changes to consider cartesian velocities
- When a cartesian velocity has to be applied, the Kinova SDK consider translation velocities in base frame and rotation velocity in end-effector fram

* Clean #ifdef guards in vpFeatureMomentAlpha

* add url for more detail infomation.

* Fix segfault and memory leak when BEST_RESIDUAL_VIRTUAL_VS or HOMOGRAPHY_ORTHOGONAL_ITERATION pose estimation method are used. Closes: #667

* Fix warnings on Ubuntu 18.04

* Fix segmentation fault in vpImageTools::warpImage due to missing out of image checks.
Use by default an alpha channel of 255 for the tests (when an image is read, alpha seems to be set to 255).
Fix bilinear interpolation typo.
Update threshold for the tests.

* Improve doc and use clang-format

* Use FLIRPTUSDK_HOME also as cmake var, not only nv var

* Introduce new functions
- jacobian
- velocity twist transformation

* Remove exception when a frame is not well decoded
- occured with FLIR Grashopper Ethernet camera
- stops visual servoing
Filter with clang-format

* Fix to turn warnings off due to librealsense2 3rd-party

* Introduce new example for visual servoing

* Exclude flir ptu from test and turn warnings off

* Add flir ptu test

* Introduce flir ptu tutorial code for IBVS

* Add how to setup LD_LIBRARY_PATH to find arsdk library at run time

* Update doc to install Flir FlyCapture SDK

* Introduce new doxygen tutorial to explain IBVS with Flir PTU

* Fix build when Flir PTU SDK is not found

* Fix warnings occuring with OSX Catalina and Xcode 11.3
- vpMath.cpp:262: warning: 'bind2nd<std::__1::minus<double>, double>' is deprecated
- vpIoTools.cpp:214: warning: 'ptr_fun<int, int>' is deprecated

$ g++ --version
Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/c++/4.2.1
Apple clang version 11.0.0 (clang-1100.0.33.16)

* Update copyright header

* Add reference to Tutorial: AprilTag marker real-time detection on iOS

* Improve iOS AprilTag detection doxygen tutorial

* Fix doxygen warnings

* Add contributor names

* Add accessors to get TopRight and BottomLeft Image points of a vpRect

* Modify to add doc, alphabetical order, rename vars starting with a letter in upper case

* Fix potential mem leak with Coin

* Introduce valgrind suppressions file

* Add new line at end of file to fix file concatenate

* Introduce additional suppressions for valgrind detected on centos 7.2

* Fix warning when building static lib

* Fix build when using stb_image for png and jpeg io when sse2 is not enabled

* Upgrade to last version 2.23

* Sync with github version

* Fix warning: comparison of unsigned expression >= 0 is always true

* Update valgrind suppressions file with false positive detected on ubuntu 12.04

* Mute warnings due to libfreenect

* Fix cmake configuration when sensor module is disabled

Co-authored-by: Gatien <44092720+Gatien-G@users.noreply.github.com>
Co-authored-by: Fabien Spindler <Fabien.Spindler@inria.fr>
Co-authored-by: s-trinh <souriya.trinh@inria.fr>
Co-authored-by: NouraNeji <55136051+NouraNeji@users.noreply.github.com>
Co-authored-by: Olivier Kermorgant <olivier_kermorgant@yahoo.fr>
Co-authored-by: Franco Fusco <francofusco93@gmail.com>
Co-authored-by: Yasutomo Shirahama <31910801+shirahamax@users.noreply.github.com>
Co-authored-by: Zubair Arif <zubair_97@yahoo.com>